//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class annualtax_hdr_tbl
    {
        public string payroll_year { get; set; }
        public string empl_id { get; set; }
        public Nullable<decimal> addl_txbl_comp_prsnt { get; set; }
        public Nullable<decimal> annual_tax_due { get; set; }
        public Nullable<decimal> wtax_prsnt_emplyr { get; set; }
        public Nullable<decimal> wtax_prev_emplyr { get; set; }
        public Nullable<decimal> ntx_basic_salary { get; set; }
        public Nullable<decimal> ntx_hol_pay_mwe { get; set; }
        public Nullable<decimal> ntx_ot_pay_mwe { get; set; }
        public Nullable<decimal> ntx_night_diff_mwe { get; set; }
        public Nullable<decimal> ntx_hzrd_pay_mwe { get; set; }
        public Nullable<decimal> ntx_13th_14th { get; set; }
        public Nullable<decimal> ntx_de_minimis { get; set; }
        public Nullable<decimal> ntx_gsis_phic_hdmf { get; set; }
        public Nullable<decimal> ntx_salaries_oth { get; set; }
        public Nullable<decimal> txbl_basic_salary { get; set; }
        public Nullable<decimal> txbl_representation { get; set; }
        public Nullable<decimal> txbl_transportation { get; set; }
        public Nullable<decimal> txbl_cola { get; set; }
        public Nullable<decimal> txbl_fh_allowance { get; set; }
        public Nullable<decimal> txbl_otherA { get; set; }
        public Nullable<decimal> txbl_otherB { get; set; }
        public Nullable<decimal> sup_commission { get; set; }
        public Nullable<decimal> sup_prof_sharing { get; set; }
        public Nullable<decimal> sup_fi_drctr_fees { get; set; }
        public Nullable<decimal> sup_13th_14th { get; set; }
        public Nullable<decimal> sup_hzrd_pay { get; set; }
        public Nullable<decimal> sup_ot_pay { get; set; }
        public Nullable<decimal> sup_otherA { get; set; }
        public Nullable<decimal> sup_otherB { get; set; }
        public Nullable<decimal> annual_txbl_income { get; set; }
        public Nullable<decimal> annual_tax_wheld { get; set; }
        public Nullable<decimal> monthly_tax_due { get; set; }
        public Nullable<decimal> tax_rate { get; set; }
        public string employer_type { get; set; }
        public string foreign_address { get; set; }
        public Nullable<decimal> stat_daily_rate { get; set; }
        public Nullable<decimal> stat_monthly_rate { get; set; }
        public Nullable<bool> min_wage_earner { get; set; }
        public string tin_employer_prev { get; set; }
        public string employer_name_prev { get; set; }
        public string employer_add_prev { get; set; }
        public string employer_zip_prev { get; set; }
        public string substituted { get; set; }
    }
}
