//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_token_tbl
    {
        public string token { get; set; }
        public string user_id { get; set; }
        public string application_name { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<System.DateTime> validuntil_datetime { get; set; }
    }
}
