//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashadv_hdr_tmp
    {
        public string ca_ctrl_nbr { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string ca_voucher_nbr { get; set; }
        public string employment_type { get; set; }
        public string ca_short_descr { get; set; }
        public string ca_descr { get; set; }
        public string catype_code { get; set; }
        public string cafund_code { get; set; }
        public string cadisb_ofcr { get; set; }
        public string ca_status { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
        public Nullable<System.DateTime> updated_dttm { get; set; }
        public string created_user_id { get; set; }
        public string updated_user_id { get; set; }
    }
}
