//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashadv_dtl_tbl
    {
        public string ca_ctrl_nbr { get; set; }
        public string voucher_nbr { get; set; }
        public string pay_period { get; set; }
    }
}
