//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_rte_users_tbl1
    {
        public System.DateTime effective_date { get; set; }
        public int route_ctrl_nbr { get; set; }
        public string role_id { get; set; }
    }
}
