//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeecard_remarks_tbl
    {
        public int remarks_id { get; set; }
        public string empl_id { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string voucher_nbr { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string addl_remarks { get; set; }
        public string user_id_created_by { get; set; }
        public Nullable<System.DateTime> created_dttm { get; set; }
    }
}
