//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_generate_payroll_not_in_annual_tbl
    {
        public string empl_id { get; set; }
        public string payroll_year { get; set; }
        public string error_message { get; set; }
        public System.DateTime created_dttm { get; set; }
    }
}
