//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generate_tax_errors_tbl
    {
        public long id { get; set; }
        public string empl_id { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string employment_type { get; set; }
        public string err_source { get; set; }
        public string err_msg { get; set; }
        public System.DateTime created_at { get; set; }
        public string batch_id { get; set; }
    }
}
