//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class idoc_rte_tbl
    {
        public string rte_code { get; set; }
        public string rte_doc_type { get; set; }
        public string rte_code_fr { get; set; }
        public string rte_code_to { get; set; }
        public string route_descr { get; set; }
        public Nullable<bool> rcvd_req_doc { get; set; }
        public Nullable<bool> rlsd_req_doc { get; set; }
        public string role_id { get; set; }
    }
}
