//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class idoc_trk_tbl
    {
        public string doc_ctrl_nbr { get; set; }
        public int route_seq { get; set; }
        public string rte_code { get; set; }
        public string vlt_code { get; set; }
        public System.DateTime doc_dttm { get; set; }
        public string doc_remarks { get; set; }
        public string doc_status { get; set; }
        public string doc_user_id { get; set; }
    }
}
