//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jo_tax_generation_queue_tbl
    {
        public long queue_id { get; set; }
        public string empl_id { get; set; }
        public string payroll_year { get; set; }
        public string requested_by { get; set; }
        public string status { get; set; }
        public System.DateTime requested_at { get; set; }
        public Nullable<System.DateTime> started_at { get; set; }
        public Nullable<System.DateTime> finished_at { get; set; }
        public string error_message { get; set; }
        public string department_code { get; set; }
    }
}
