//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRIS_DEVEntities : DbContext
    {
        public HRIS_DEVEntities()
            : base("name=HRIS_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<payrollemployee_tax_tbl> payrollemployee_tax_tbl { get; set; }
        public virtual DbSet<personnel_tbl> personnel_tbl { get; set; }
        public virtual DbSet<usersprofile_tbl> usersprofile_tbl { get; set; }
        public virtual DbSet<application_token_tbl> application_token_tbl { get; set; }
        public virtual DbSet<empl_taxwithheld_tbl> empl_taxwithheld_tbl { get; set; }
        public virtual DbSet<payrollemployee_tax_phic_rece_tbl> payrollemployee_tax_phic_rece_tbl { get; set; }
    
        public virtual ObjectResult<sp_empltaxwithheld_tbl_for_apprvl_Result> sp_empltaxwithheld_tbl_for_apprvl(string p_employment_type)
        {
            var p_employment_typeParameter = p_employment_type != null ?
                new ObjectParameter("p_employment_type", p_employment_type) :
                new ObjectParameter("p_employment_type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_empltaxwithheld_tbl_for_apprvl_Result>("sp_empltaxwithheld_tbl_for_apprvl", p_employment_typeParameter);
        }
    
        public virtual int sp_payrollemployee_tax_hdr_tbl_update(string par_empl_id, Nullable<System.DateTime> par_effective_date, string par_rcrd_status, string par_user_id_updated_by)
        {
            var par_empl_idParameter = par_empl_id != null ?
                new ObjectParameter("par_empl_id", par_empl_id) :
                new ObjectParameter("par_empl_id", typeof(string));
    
            var par_effective_dateParameter = par_effective_date.HasValue ?
                new ObjectParameter("par_effective_date", par_effective_date) :
                new ObjectParameter("par_effective_date", typeof(System.DateTime));
    
            var par_rcrd_statusParameter = par_rcrd_status != null ?
                new ObjectParameter("par_rcrd_status", par_rcrd_status) :
                new ObjectParameter("par_rcrd_status", typeof(string));
    
            var par_user_id_updated_byParameter = par_user_id_updated_by != null ?
                new ObjectParameter("par_user_id_updated_by", par_user_id_updated_by) :
                new ObjectParameter("par_user_id_updated_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_payrollemployee_tax_hdr_tbl_update", par_empl_idParameter, par_effective_dateParameter, par_rcrd_statusParameter, par_user_id_updated_byParameter);
        }
    
        public virtual ObjectResult<sp_payrollemployee_tax_tbl_for_apprvl_Result> sp_payrollemployee_tax_tbl_for_apprvl(string par_year, string par_rcrd_status)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_rcrd_statusParameter = par_rcrd_status != null ?
                new ObjectParameter("par_rcrd_status", par_rcrd_status) :
                new ObjectParameter("par_rcrd_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollemployee_tax_tbl_for_apprvl_Result>("sp_payrollemployee_tax_tbl_for_apprvl", par_yearParameter, par_rcrd_statusParameter);
        }
    
        public virtual ObjectResult<sp_payrollemployee_tax_tbl_for_apprvl_NE_Result> sp_payrollemployee_tax_tbl_for_apprvl_NE(string par_year, string par_rcrd_status)
        {
            var par_yearParameter = par_year != null ?
                new ObjectParameter("par_year", par_year) :
                new ObjectParameter("par_year", typeof(string));
    
            var par_rcrd_statusParameter = par_rcrd_status != null ?
                new ObjectParameter("par_rcrd_status", par_rcrd_status) :
                new ObjectParameter("par_rcrd_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_payrollemployee_tax_tbl_for_apprvl_NE_Result>("sp_payrollemployee_tax_tbl_for_apprvl_NE", par_yearParameter, par_rcrd_statusParameter);
        }
    }
}
