//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class obr_tracking_tbl
    {
        public string payroll_year { get; set; }
        public string payroll_registry_nbr { get; set; }
        public Nullable<decimal> sum_gross_pay { get; set; }
        public Nullable<decimal> sum_oth_amt { get; set; }
        public Nullable<decimal> sum_oth_amt1 { get; set; }
        public Nullable<decimal> sum_oth_amt2 { get; set; }
        public Nullable<decimal> sum_oth_amt3 { get; set; }
        public Nullable<decimal> tot_amt { get; set; }
    }
}
