//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistryaccounting_hdr_ret_tbl
    {
        public string voucher_nbr { get; set; }
        public string tran_year { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string payroll_registry_descr { get; set; }
        public string payroll_group_nbr { get; set; }
        public string department_code { get; set; }
        public Nullable<System.DateTime> rcvd_dttm { get; set; }
        public string rcvd_by_user { get; set; }
        public Nullable<System.DateTime> audit_rcvd_dttm { get; set; }
        public string audit_rcvd_user { get; set; }
        public Nullable<System.DateTime> audited_dttm { get; set; }
        public string audited_by_user { get; set; }
        public Nullable<System.DateTime> posting_rcvd_dttm { get; set; }
        public string posting_rcvd_by_user { get; set; }
        public Nullable<System.DateTime> posted_dttm { get; set; }
        public string posted_by_user { get; set; }
        public Nullable<System.DateTime> review_dttm { get; set; }
        public string reviewed_by_user { get; set; }
        public Nullable<System.DateTime> rlsd_dttm { get; set; }
        public string rlsd_by_user { get; set; }
        public Nullable<System.DateTime> unposted_dttm { get; set; }
        public string unposted_by_user { get; set; }
        public string payroll_source { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string remarks_return { get; set; }
        public System.DateTime returned_dttm { get; set; }
        public string returned_by_user { get; set; }
    }
}
