//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrollregistry_dtl_unpost_tbl
    {
        public string voucher_nbr { get; set; }
        public string tran_year { get; set; }
        public string empl_id { get; set; }
        public System.DateTime date_unposted { get; set; }
        public string unposted_by_user { get; set; }
        public string unpost_reason { get; set; }
    }
}
