//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remittance_or_tbl
    {
        public string remittance_ctrl_nbr { get; set; }
        public string remittance_or_nbr { get; set; }
        public Nullable<System.DateTime> period_covered { get; set; }
        public Nullable<System.DateTime> remittance_or_date { get; set; }
        public string remittance_status { get; set; }
    }
}
