//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remittance_dtl_gsis_flt_tbl
    {
        public string remittance_ctrl_nbr { get; set; }
        public string empl_id { get; set; }
        public string voucher_nbr { get; set; }
        public Nullable<decimal> float_amount_ps { get; set; }
        public Nullable<decimal> float_amount_gs { get; set; }
        public Nullable<decimal> float_sif_gs { get; set; }
        public Nullable<decimal> float_gsis_uoli { get; set; }
        public Nullable<decimal> float_gsis_ehp { get; set; }
        public Nullable<decimal> float_gsis_hip { get; set; }
        public Nullable<decimal> float_gsis_ceap { get; set; }
        public Nullable<decimal> float_gsis_addl_ins { get; set; }
        public Nullable<decimal> float_gsis_conso_ln { get; set; }
        public Nullable<decimal> float_gsis_policy_reg_ln { get; set; }
        public Nullable<decimal> float_gsis_policy_opt_ln { get; set; }
        public Nullable<decimal> float_gsis_emergency_ln { get; set; }
        public Nullable<decimal> float_gsis_ecard_ln { get; set; }
        public Nullable<decimal> float_gsis_educ_asst_ln { get; set; }
        public Nullable<decimal> float_gsis_real_state_ln { get; set; }
        public Nullable<decimal> float_gsis_sos_ln { get; set; }
        public Nullable<decimal> float_gsis_help { get; set; }
        public string float_status { get; set; }
        public Nullable<decimal> float_other_loan1 { get; set; }
        public Nullable<decimal> float_other_loan2 { get; set; }
        public Nullable<decimal> float_other_loan3 { get; set; }
    }
}
