//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remittance_dtl_float_tbl
    {
        public string remittance_ctrl_nbr { get; set; }
        public string empl_id { get; set; }
        public decimal voucher_nbr { get; set; }
        public Nullable<decimal> float_amount_gs { get; set; }
        public Nullable<decimal> float_amount_ps { get; set; }
        public string float_status { get; set; }
    }
}
