//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remittance_cert_tbl
    {
        public string empl_id { get; set; }
        public string remittancetype_code { get; set; }
        public string or_nbr { get; set; }
        public System.DateTime or_date { get; set; }
        public string remittance_year { get; set; }
        public string remittance_month { get; set; }
        public Nullable<decimal> amount_ps { get; set; }
        public Nullable<decimal> amount_gs { get; set; }
        public string cert_status { get; set; }
        public string created_by_user { get; set; }
        public Nullable<System.DateTime> created_by_dttm { get; set; }
        public string updated_by_user { get; set; }
        public Nullable<System.DateTime> updated_by_dttm { get; set; }
    }
}
