//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remittance_dtl_tax_tbl
    {
        public string remittance_ctrl_nbr { get; set; }
        public string empl_id { get; set; }
        public string voucher_nbr { get; set; }
        public string payroll_source { get; set; }
        public Nullable<decimal> basic_tax { get; set; }
        public Nullable<decimal> ot_tax { get; set; }
        public Nullable<decimal> wtax_2perc { get; set; }
        public Nullable<decimal> wtax_3perc { get; set; }
        public Nullable<decimal> wtax_5perc { get; set; }
        public Nullable<decimal> wtax_8perc { get; set; }
        public Nullable<decimal> wtax_10perc { get; set; }
        public Nullable<decimal> wtax_15perc { get; set; }
        public string remittance_ctrl_ref { get; set; }
        public string remittance_status { get; set; }
        public string or_nbr { get; set; }
        public Nullable<System.DateTime> or_date { get; set; }
    }
}
