//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_tbl
    {
        public string seq_no { get; set; }
        public string tax_year { get; set; }
        public Nullable<decimal> lower_limit { get; set; }
        public Nullable<decimal> upper_limit { get; set; }
        public Nullable<decimal> tax_on_lower_limit { get; set; }
        public Nullable<decimal> tax_on_excess { get; set; }
    }
}
