//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_cashadv_for_transmmittal_list
    {
        public string ca_voucher_nbr { get; set; }
        public string ca_descr { get; set; }
        public string ca_short_descr { get; set; }
        public string employment_type { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string cafund_code { get; set; }
        public string catype_code { get; set; }
        public string voucher_nbr { get; set; }
        public Nullable<decimal> net_pay { get; set; }
        public Nullable<decimal> net_pay1 { get; set; }
        public Nullable<decimal> net_pay2 { get; set; }
        public string payrolltemplate_code { get; set; }
        public string payroll_group_nbr { get; set; }
        public string payroll_registry_descr { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string report_filename { get; set; }
        public string pay_period { get; set; }
    }
}
