//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CE_employee_income_for_annual_tax
    {
        public string empl_id { get; set; }
        public string employment_type { get; set; }
        public Nullable<int> effective_year { get; set; }
        public Nullable<int> effective_month { get; set; }
        public System.DateTime effective_date { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> daily_rate { get; set; }
        public decimal pera_amt_RE { get; set; }
        public decimal pera_amt_CE { get; set; }
        public decimal clothing_allw { get; set; }
        public decimal productivity_ei { get; set; }
        public decimal pay_13th_month { get; set; }
        public decimal pay_14th_month { get; set; }
        public decimal cash_gift { get; set; }
        public decimal subsistence_allw { get; set; }
        public decimal laundry_allw { get; set; }
        public decimal hazard_p { get; set; }
        public decimal loyalty_bonus { get; set; }
    }
}
