//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_idoc_trk_tbl_2be_rlsd
    {
        public string doc_ctrl_nbr { get; set; }
        public Nullable<int> route_seq { get; set; }
        public string rte_code { get; set; }
        public string vlt_code { get; set; }
        public string route_descr { get; set; }
        public System.DateTime doc_dttm { get; set; }
        public string doc_remarks { get; set; }
        public string doc_status { get; set; }
        public string doc_user_id { get; set; }
        public string document_status_descr { get; set; }
        public Nullable<bool> rcvd_req_doc { get; set; }
        public Nullable<bool> rlsd_req_doc { get; set; }
        public string required_doc_type { get; set; }
        public string role_id { get; set; }
        public string payroll_registry_descr { get; set; }
        public Nullable<decimal> gross_pay { get; set; }
        public Nullable<decimal> net_pay { get; set; }
        public string payrolltemplate_code { get; set; }
        public string payrolltemplate_descr { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public string docmnt_type { get; set; }
        public string doc_fund_subcode { get; set; }
        public string doc_pbo_nbr { get; set; }
        public string doc_cafoa { get; set; }
        public string doc_voucher_nbr { get; set; }
        public string doc_pto_nbr { get; set; }
    }
}
