//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lbp_transmittal_list
    {
        public string batch_nbr { get; set; }
        public string empl_id { get; set; }
        public string atm_acct_nbr { get; set; }
        public string employee_name { get; set; }
        public string netpay { get; set; }
    }
}
