//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrollemployeemaster_info_HRIS_ACT
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string employment_type { get; set; }
        public string employmenttype_description { get; set; }
        public string effective_date { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<decimal> daily_rate { get; set; }
        public string department_code { get; set; }
        public string position_title1 { get; set; }
        public string department_name1 { get; set; }
        public string position_code { get; set; }
    }
}
