//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_phic_share_empl_tbl_rc
    {
        public string empl_id { get; set; }
        public string department_code { get; set; }
        public string group_code { get; set; }
        public Nullable<decimal> empl_no_share { get; set; }
        public string position_long_title { get; set; }
        public Nullable<decimal> rate_amount { get; set; }
        public string employee_name { get; set; }
        public string empl_type { get; set; }
        public string group_description { get; set; }
        public string employment_type { get; set; }
        public string group_class { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string payroll_year { get; set; }
        public Nullable<decimal> tax_rate { get; set; }
        public Nullable<decimal> wtax_amt { get; set; }
        public string rcrd_status { get; set; }
    }
}
