//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payrolltemplate_tbl_list
    {
        public string payrolltemplate_code { get; set; }
        public string payrolltemplate_descr { get; set; }
        public string payrolltemplate_short_descr { get; set; }
        public string payrolltemplate_type { get; set; }
        public string employment_type { get; set; }
        public string report_filename { get; set; }
        public string crud_name { get; set; }
        public string payment_mode { get; set; }
    }
}
