//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_personneladdress_contact_id_tbl_HRIS_ACT
    {
        public string empl_id { get; set; }
        public string zip_code { get; set; }
        public string address_info { get; set; }
        public string mobile_no { get; set; }
    }
}
