//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_phic_share_rece_tbl_ACT
    {
        public string empl_id { get; set; }
        public string employee_name { get; set; }
        public string department_code { get; set; }
        public string group_code { get; set; }
        public decimal empl_no_share { get; set; }
        public string position_long_title { get; set; }
        public decimal rate_amount { get; set; }
        public string empl_type { get; set; }
        public string bir_class { get; set; }
        public bool with_sworn { get; set; }
        public bool fixed_rate { get; set; }
        public decimal total_gross_pay { get; set; }
        public bool dedct_status { get; set; }
        public string rcrd_status { get; set; }
        public decimal w_tax_perc { get; set; }
        public decimal bus_tax_perc { get; set; }
        public decimal vat_perc { get; set; }
        public decimal exmpt_amt { get; set; }
        public string tax_year_effective_date { get; set; }
        public string tax_year { get; set; }
        public string employment_type { get; set; }
    }
}
