//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_remittance_dtl_all
    {
        public string or_nbr { get; set; }
        public string empl_id { get; set; }
        public string payroll_period_month { get; set; }
        public string payroll_year { get; set; }
        public Nullable<decimal> remittance_amt { get; set; }
    }
}
