//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_remittance_OTHERS09
    {
        public string empl_id { get; set; }
        public string employment_type { get; set; }
        public string voucher_nbr { get; set; }
        public Nullable<int> posted_year { get; set; }
        public Nullable<int> posted_month { get; set; }
        public string payroll_registry_descr { get; set; }
        public Nullable<decimal> network_ln { get; set; }
        public decimal nico_ln { get; set; }
        public decimal nhmfc_hsing { get; set; }
        public decimal philamlife_ps { get; set; }
        public decimal ccmpc_ln { get; set; }
        public string employee_name { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix_name { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
    }
}
