//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_remittance_info_ALL1
    {
        public string remittance_ctrl_nbr { get; set; }
        public string remittance_year { get; set; }
        public string remittance_month { get; set; }
        public string employment_type { get; set; }
        public string remittancetype_code { get; set; }
        public string remittancetype_descr { get; set; }
        public string remittance_descr { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string voucher_nbr { get; set; }
        public string empl_id { get; set; }
        public Nullable<decimal> p_gsis_gs { get; set; }
        public Nullable<decimal> p_gsis_ps { get; set; }
        public Nullable<decimal> p_sif_gs { get; set; }
        public Nullable<decimal> p_gsis_uoli { get; set; }
        public Nullable<decimal> p_gsis_ehp { get; set; }
        public Nullable<decimal> p_gsis_hip { get; set; }
        public Nullable<decimal> p_gsis_ceap { get; set; }
        public Nullable<decimal> p_gsis_addl_ins { get; set; }
        public Nullable<decimal> p_gsis_conso_ln { get; set; }
        public Nullable<decimal> p_gsis_policy_reg_ln { get; set; }
        public Nullable<decimal> p_gsis_policy_opt_ln { get; set; }
        public Nullable<decimal> p_gsis_emergency_ln { get; set; }
        public Nullable<decimal> p_gsis_ecard_ln { get; set; }
        public Nullable<decimal> p_gsis_educ_asst_ln { get; set; }
        public Nullable<decimal> p_gsis_real_state_ln { get; set; }
        public Nullable<decimal> p_gsis_sos_ln { get; set; }
        public Nullable<decimal> p_gsis_help { get; set; }
        public Nullable<decimal> u_gsis_gs { get; set; }
        public Nullable<decimal> u_gsis_ps { get; set; }
        public Nullable<decimal> u_sif_gs { get; set; }
        public Nullable<decimal> u_gsis_uoli { get; set; }
        public Nullable<decimal> u_gsis_ehp { get; set; }
        public Nullable<decimal> u_gsis_hip { get; set; }
        public Nullable<decimal> u_gsis_ceap { get; set; }
        public Nullable<decimal> u_gsis_addl_ins { get; set; }
        public Nullable<decimal> u_gsis_conso_ln { get; set; }
        public Nullable<decimal> u_gsis_policy_reg_ln { get; set; }
        public Nullable<decimal> u_gsis_policy_opt_ln { get; set; }
        public Nullable<decimal> u_gsis_emergency_ln { get; set; }
        public Nullable<decimal> u_gsis_ecard_ln { get; set; }
        public Nullable<decimal> u_gsis_educ_asst_ln { get; set; }
        public Nullable<decimal> u_gsis_real_state_ln { get; set; }
        public Nullable<decimal> u_gsis_sos_ln { get; set; }
        public Nullable<decimal> u_gsis_help { get; set; }
        public Nullable<decimal> o_gsis_gs { get; set; }
        public Nullable<decimal> o_gsis_ps { get; set; }
        public string remittance_status { get; set; }
        public string remittance_status_descr { get; set; }
        public Nullable<int> or_nbr { get; set; }
        public Nullable<System.DateTime> or_date { get; set; }
        public Nullable<decimal> p_other_loan1 { get; set; }
        public Nullable<decimal> p_other_loan2 { get; set; }
        public Nullable<decimal> u_other_loan1 { get; set; }
        public Nullable<decimal> u_other_loan2 { get; set; }
        public Nullable<decimal> o_other_loan1 { get; set; }
        public Nullable<decimal> o_other_loan2 { get; set; }
        public Nullable<decimal> p_other_loan3 { get; set; }
        public Nullable<decimal> u_other_loan3 { get; set; }
        public Nullable<decimal> o_other_loan3 { get; set; }
        public Nullable<decimal> p_other_loan5 { get; set; }
        public int u_other_loan5 { get; set; }
        public int o_other_loan5 { get; set; }
        public Nullable<decimal> payroll_amount_gs { get; set; }
        public Nullable<decimal> payroll_amount_ps { get; set; }
        public Nullable<decimal> uploaded_amount_gs { get; set; }
        public Nullable<decimal> uploaded_amount_ps { get; set; }
        public Nullable<decimal> override_amount_gs { get; set; }
        public Nullable<decimal> override_amount_ps { get; set; }
        public string membership_program { get; set; }
        public string detailed_remarks { get; set; }
        public Nullable<decimal> payroll_amount { get; set; }
        public string remittance_ctrl_ref { get; set; }
        public Nullable<decimal> uploaded_amount { get; set; }
        public Nullable<decimal> gfaleducnl_ln { get; set; }
    }
}
