//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_remittance_GSIS
    {
        public string empl_id { get; set; }
        public string employment_type { get; set; }
        public string voucher_nbr { get; set; }
        public Nullable<int> posted_year { get; set; }
        public Nullable<int> posted_month { get; set; }
        public string payroll_registry_descr { get; set; }
        public Nullable<decimal> gsis_gs { get; set; }
        public Nullable<decimal> gsis_ps { get; set; }
        public Nullable<decimal> sif_gs { get; set; }
        public Nullable<decimal> gsis_uoli { get; set; }
        public Nullable<decimal> gsis_ehp { get; set; }
        public Nullable<decimal> gsis_hip { get; set; }
        public Nullable<decimal> gsis_ceap { get; set; }
        public Nullable<decimal> gsis_addl_ins { get; set; }
        public Nullable<decimal> gsis_conso_ln { get; set; }
        public Nullable<decimal> gsis_policy_reg_ln { get; set; }
        public Nullable<decimal> gsis_policy_opt_ln { get; set; }
        public Nullable<decimal> gsis_emergency_ln { get; set; }
        public Nullable<decimal> gsis_ecard_ln { get; set; }
        public Nullable<decimal> gsis_educ_asst_ln { get; set; }
        public Nullable<decimal> gsis_real_state_ln { get; set; }
        public Nullable<decimal> gsis_sos_ln { get; set; }
        public Nullable<decimal> gsis_help { get; set; }
        public string employee_name { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string suffix_name { get; set; }
        public string payroll_registry_nbr { get; set; }
        public string payroll_year { get; set; }
        public string payroll_month { get; set; }
        public Nullable<decimal> other_loan1 { get; set; }
        public Nullable<decimal> other_loan2 { get; set; }
        public Nullable<decimal> other_loan3 { get; set; }
        public Nullable<decimal> other_loan4 { get; set; }
        public Nullable<decimal> other_loan5 { get; set; }
    }
}
