//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rata_rate_sked_tbl_list2
    {
        public int no_of_days_max { get; set; }
        public int rate_percentage { get; set; }
        public Nullable<double> rate_percentage_1 { get; set; }
        public string rate_type { get; set; }
    }
}
