//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_ePAccount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_subdepartments_tbl_list
    {
        public string subdepartment_code { get; set; }
        public string subdepartment_short_name { get; set; }
        public string subdepartment_name1 { get; set; }
        public string subdepartment_name2 { get; set; }
    }
}
